// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBHkO7uwxT42M6vA8Ma00bJXJ6BhDaa4U',
    appId: '1:752640945309:web:901febf1297be8779c3874',
    messagingSenderId: '752640945309',
    projectId: 'milkman-79e58',
    authDomain: 'milkman-79e58.firebaseapp.com',
    storageBucket: 'milkman-79e58.firebasestorage.app',
    measurementId: 'G-Z4HZ3L19X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWAMED5KN5LOuduJgbX_GOxVWXH2RZcQ',
    appId: '1:752640945309:android:86092447bea0753c9c3874',
    messagingSenderId: '752640945309',
    projectId: 'milkman-79e58',
    storageBucket: 'milkman-79e58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGcrFKGqrZVEHfa29yO7ZjYN5SULTjhM',
    appId: '1:752640945309:ios:d5f66d4f45e50cb29c3874',
    messagingSenderId: '752640945309',
    projectId: 'milkman-79e58',
    storageBucket: 'milkman-79e58.firebasestorage.app',
    iosBundleId: 'com.example.milkman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGcrFKGqrZVEHfa29yO7ZjYN5SULTjhM',
    appId: '1:752640945309:ios:d5f66d4f45e50cb29c3874',
    messagingSenderId: '752640945309',
    projectId: 'milkman-79e58',
    storageBucket: 'milkman-79e58.firebasestorage.app',
    iosBundleId: 'com.example.milkman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBHkO7uwxT42M6vA8Ma00bJXJ6BhDaa4U',
    appId: '1:752640945309:web:f0874197a53653a39c3874',
    messagingSenderId: '752640945309',
    projectId: 'milkman-79e58',
    authDomain: 'milkman-79e58.firebaseapp.com',
    storageBucket: 'milkman-79e58.firebasestorage.app',
    measurementId: 'G-H58DFLME6V',
  );
}
